/**
 * Generated per-element React wrappers for every Core UI_Element (tasks 14.3/14.7).
 *
 * This module is the single place where the React_Adapter turns Core's
 * `UI_ELEMENT_BINDINGS` table (the framework-agnostic description of every
 * `playerstack-*` Custom Element: its tag, observed attributes and request
 * events) into a map of thin React components. Each entry is produced by
 * `createReactElement(binding)` (Req 7, Req 16), so the full set of elements is
 * generated by MAPPING over the bindings rather than hand-writing one component
 * per element. Adding/removing an element in Core automatically flows through
 * here without touching this file.
 *
 * The map is keyed by the PascalCase form of the Custom Element tag (e.g.
 * `playerstack-play-button` -> `PlayerstackPlayButton`) so skins can import a
 * readable component name, and Core's UI_Elements are registered once via
 * `registerPlayerstackElements()` the first time this module is imported so the
 * Custom Elements exist before any wrapper renders (Style_Auto_Injection then
 * applies the Style_Layer on connect — the consumer imports no CSS, Req 7.4).
 */
import { UI_ELEMENT_BINDINGS } from '@playerstack/core/adapters/framework';
import { registerPlayerstackElements } from '@playerstack/core/ui';

import { createReactElement } from '@adapter/createReactElement';

/**
 * Converts a `playerstack-*` Custom Element tag into its PascalCase React
 * component key. Example: `playerstack-time-slider` -> `PlayerstackTimeSlider`.
 *
 * @param {string} tagName - The Custom Element tag from the binding.
 * @returns {string} The PascalCase component key.
 */
function tagNameToComponentKey(tagName) {
  return tagName
    .split('-')
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

/**
 * Register Core's UI_Elements exactly once at module load. `registerPlayerstackElements`
 * is idempotent (it skips names already defined), so importing this module from
 * multiple entry points — or alongside other bundles that ship Core — is safe.
 * Registration must happen before the wrappers render so `document.createElement`
 * yields upgraded Custom Elements that adopt the Style_Layer on connect (Req 7.4).
 */
if (typeof window !== 'undefined' && typeof window.customElements !== 'undefined') {
  registerPlayerstackElements();
}

/**
 * The generated map `{ PlayerstackPlayButton: <component>, ... }`, one React
 * component per Core UI_Element, all driven by `UI_ELEMENT_BINDINGS`.
 */
export const PlayerstackElements = UI_ELEMENT_BINDINGS.reduce((map, binding) => {
  map[tagNameToComponentKey(binding.tagName)] = createReactElement(binding);
  return map;
}, {});

// Named exports for ergonomic imports in the skin composition. Kept explicit so
// editors autocomplete the element components and tree-shaking stays precise.
export const PlayerstackMediaController = PlayerstackElements.PlayerstackMediaController;
export const PlayerstackPlayButton = PlayerstackElements.PlayerstackPlayButton;
export const PlayerstackVolume = PlayerstackElements.PlayerstackVolume;
export const PlayerstackTimeSlider = PlayerstackElements.PlayerstackTimeSlider;
export const PlayerstackPlayTime = PlayerstackElements.PlayerstackPlayTime;
export const PlayerstackSettings = PlayerstackElements.PlayerstackSettings;
export const PlayerstackFullscreenButton = PlayerstackElements.PlayerstackFullscreenButton;
export const PlayerstackPipButton = PlayerstackElements.PlayerstackPipButton;
export const PlayerstackCaptions = PlayerstackElements.PlayerstackCaptions;
export const PlayerstackChapters = PlayerstackElements.PlayerstackChapters;
export const PlayerstackHeatmap = PlayerstackElements.PlayerstackHeatmap;
export const PlayerstackContextMenu = PlayerstackElements.PlayerstackContextMenu;
export const PlayerstackSpinner = PlayerstackElements.PlayerstackSpinner;
export const PlayerstackPlayState = PlayerstackElements.PlayerstackPlayState;
export const PlayerstackTopState = PlayerstackElements.PlayerstackTopState;
export const PlayerstackPreventedTip = PlayerstackElements.PlayerstackPreventedTip;
export const PlayerstackAudioControls = PlayerstackElements.PlayerstackAudioControls;
export const PlayerstackAdOverlay = PlayerstackElements.PlayerstackAdOverlay;
export const PlayerstackLiveIndicator = PlayerstackElements.PlayerstackLiveIndicator;
export const PlayerstackDoubleTap = PlayerstackElements.PlayerstackDoubleTap;
export const PlayerstackIcon = PlayerstackElements.PlayerstackIcon;
export const PlayerstackNavButtons = PlayerstackElements.PlayerstackNavButtons;
export const PlayerstackMobileSettings = PlayerstackElements.PlayerstackMobileSettings;
export const PlayerstackSpritePreview = PlayerstackElements.PlayerstackSpritePreview;
export const PlayerstackLiveAd = PlayerstackElements.PlayerstackLiveAd;
